services:
  - type: web
    name: africa-soko-backend
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: africa-soko-db
          property: connectionString

databases:
  - name: africa-soko-db
    databaseName: africa_soko
    user: africa_soko_user
    plan: free
