services:
  - type: web
    name: africa-soko-backend
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: africa-soko-db
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: africa-soko-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: africa-soko-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: africa-soko-db
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: africa-soko-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: africa-soko-db
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_USER_DEFAULT_PASSWORD
        generateValue: true

databases:
  - name: africa-soko-db
    databaseName: africa_soko
    user: africa_soko_user
    plan: free
